export const courseType = [
  { id: 'onDemand', label: 'On-Demand Courses', shortLabel: 'On-Demand' },
  { id: 'onlineProgram', label: 'Online Programs', shortLabel: 'Online' },
  { id: 'offlineProgram', label: 'Offline Programs', shortLabel: 'Offline' },
];

export const courses = [
  {
    id: 'cloud-computing-masterclass',
    paymentCourseId: 1,
    category: 'onlineProgram',
    title: 'Cloud Computing Masterclass',
    instructor: 'Alex Rivera',
    description:
      'Master enterprise architecture, serverless deployments, and hybrid cloud strategies using the Azure stack and innovation framework.',
    level: 'Advanced',
    courseArea: 'Development',
    topic: 'Cloud',
    format: 'Live Online',
    date: 'June 15 - June 17',
    time: '10:00 AM - 01:00 PM',
    platform: 'Zoom Platform',
    duration: '12 Weeks',
    startsIn: 'Starts in 2 days',
    price: 1299,
    seatsLeft: 8,
    accent: 'blue',
    sessions: [
      {
        id: 'summer-intake',
        title: 'Session 1: Summer Intake',
        date: 'June 15 - June 17, 2024',
        time: '09:00 - 17:00 EST',
      },
      {
        id: 'late-summer',
        title: 'Session 2: Late Summer Intake',
        date: 'July 20 - July 22, 2024',
        time: '09:00 - 17:00 EST',
      },
    ],
  },
  
  {
    id: 'cybersecurity-essentials',
    category: 'onlineProgram',
    title: 'Cybersecurity Essentials',
    instructor: 'Sarah Chen',
    description:
      'Build a practical security foundation across network defense, identity, risk reviews, and incident response.',
    level: 'Intermediate',
    courseArea: 'Business',
    topic: 'Security',
    format: 'Live Online',
    date: 'June 20 - June 22',
    time: '02:00 PM - 05:00 PM',
    platform: 'Zoom Platform',
    duration: '8 Weeks',
    startsIn: 'Starts in 5 days',
    price: 899,
    seatsLeft: 12,
    accent: 'purple',
  },
  {
    id: 'react-essentials',
    paymentCourseId: 2,
    category: 'onDemand',
    title: 'React Essentials',
    instructor: 'Maya Iyer',
    description:
      'Build modern UIs with components, hooks, state management, and practical patterns you can reuse.',
    level: 'Beginner',
    courseArea: 'Development',
    topic: 'Frontend',
    format: 'Self Paced',
    date: 'Available Now',
    time: 'Anytime',
    platform: 'Learning Portal',
    duration: '6 Hours',
    startsIn: 'Instant access',
    price: 299,
    seatsLeft: null,
    imageUrl: '',
    accent: 'orange',
  },
  {
    id: 'advanced-react-patterns',
    paymentCourseId: 3,
    category: 'onDemand',
    title: ' Advanced React Patterns',
    instructor: 'Noah Brooks',
    description:
      'Level up reusable component design, performance work, data flows, and real production ergonomics.',
    level: 'Advanced',
    courseArea: 'Development',
    topic: 'Frontend',
    format: 'Self Paced',
    date: 'Available Now',
    time: 'Anytime',
    platform: 'Learning Portal',
    duration: '9 Hours',
    startsIn: 'Instant access',
    price: 399,
    seatsLeft: null,
    imageUrl: '',
    accent: 'blue',
  },
  {
    id: 'data-science-bootcamp',
    paymentCourseId: 4,
    category: 'offlineProgram',
    title: 'Data Science Bootcamp',
    instructor: 'Priya Mehta',
    description:
      'In-person bootcamp covering Python, machine learning, analytics workflows, and real-world projects.',
    level: 'Intermediate',
    courseArea: 'Marketing',
    topic: 'Data',
    format: 'In Person',
    date: 'July 05 - July 19',
    time: '10:00 AM - 04:00 PM',
    platform: 'Bengaluru Campus',
    location: 'Bengaluru',
    duration: '2 Weeks',
    startsIn: 'Starts in 12 days',
    price: 1499,
    seatsLeft: 6,
    accent: 'green',
  },
  {
    id: 'fullstack-lab',
    paymentCourseId: 5,
    category: 'offlineProgram',
    title: 'Fullstack Lab',
    instructor: 'Chris Morgan',
    description:
      'Build and ship a complete web product with backend APIs, database models, testing, and deployment.',
    level: 'Beginner',
    courseArea: 'Development',
    topic: 'Fullstack',
    format: 'In Person',
    date: 'August 08 - August 16',
    time: '09:30 AM - 03:30 PM',
    platform: 'Hyderabad Campus',
    location: 'Hyderabad',
    duration: '9 Days',
    startsIn: 'Starts in 18 days',
    price: 1199,
    seatsLeft: 10,
    accent: 'orange',
  },
];

export function getCourseById(courseId) {
  return courses.find((course) => course.id === courseId);
}
